import type { AppProps } from 'next/app'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useState } from 'react'
import { ThemeProvider } from 'styled-components'
import GlobalStyle, { darkTheme, lightTheme } from '../styles/globalStyled'
import * as Styled from '../styles/main'
import '@fontsource/prompt'
const Navbar = dynamic(() => import('../components/Navbar'), { ssr: false })

function MyApp({ Component, pageProps }: AppProps) {
  const [isDarkTheme, setIsDarkTheme] = useState<boolean>(false)

  return (
    <>
      <Head>
        <title>{pageProps?.header?.title || 'pizza'}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ThemeProvider theme={isDarkTheme ? darkTheme : lightTheme}>
        <GlobalStyle />
        <Styled.Container>
          {/* <Styled.ThemeButton
            onClick={() => setIsDarkTheme((prev: boolean) => !prev)}
          >
            {isDarkTheme ? '🌙' : '🌝'}
          </Styled.ThemeButton> */}
          <Component {...pageProps} />
          <Navbar />
        </Styled.Container>
      </ThemeProvider>
    </>
  )
}

export default MyApp
